Improved category photo presentation
grief-matters/whygriefmatters.org pull request #76
Opened 2024-12-07 09:27 UTC by aditya000028

### Changes 

- upgraded tailwind version
- adjusted xl image width request size 
- adjusted font sizes for larger screens of `supTitle`
- deleted older css
- added tailwind for larger screen sizes to display according to design 

### Screenshots

##### XL Screen:
![image](https://github.com/user-attachments/assets/95b72896-db35-47e8-81ee-b8cfa93ffc82)

##### MD Screen:
![image](https://github.com/user-attachments/assets/9ee38d61-31ec-46d1-b856-ef2877e29299)

##### iPhone:
![image](https://github.com/user-attachments/assets/ce1ef3ec-18ba-4309-8b99-3163dca9db8d)

Closes #70

2024-12-11 19:52 UTC, danlechambre requested changes

2024-12-11 19:52 UTC, danlechambre commented on src/ui/PageHeader.astro
As I alluded to I'm really not sure about the design here. Let's focus on the aspect ratio thing for now.

Let's continue with the switch to the `<img />` element with srcset to solve the fetching of overly large images. The widest image you fetch should not exceed the size of the container. Then just optimise for each breakpoint.

I'd like you to use the `<Container />` component to constrain the header width to the same width as the content, which should at least solve the long "letterbox" type photos - but otherwise we'll more or less leave the design as it is for now until I get time to address the design issues properly with Camille.

2024-12-14 00:43 UTC, aditya000028 commented
Thanks for your comments Dan. I think the quickest way to address these issues for me to create another branch and just port over the `PageHeader` changes along with addressing your `PageHeader` comments. I will also add the `.gitattributes` file as well. Will have a PR up as soon as I can.

2024-12-16 03:42 UTC, aditya000028 commented
Closing PR. Please see newer #82 addressing changes

2024-12-16 03:42 UTC, closed without merging