Improved category photo presentation
grief-matters/whygriefmatters.org pull request #82
Opened 2024-12-16 03:39 UTC by aditya000028

## Changes:
- Added `.gitattributes` file for normalizing line endings
- reduce width requested of `xl` image down to 1400 from 2560
- Used `Container` component to restrict header size
- Removed older css breakpoint code
- Added tailwind classes for better font scaling

## Screenshots:
#### XL:
![image](https://github.com/user-attachments/assets/c2f6755d-e0df-4915-9bfc-969a5f3261c9)

#### MD: 
![image](https://github.com/user-attachments/assets/177c7203-a0ab-4a0c-9546-db9b0e72080b)

#### SM:
![image](https://github.com/user-attachments/assets/3fc5d13f-2e81-4a05-a7a8-7f08a1ed6266)

#### iPhone:
![image](https://github.com/user-attachments/assets/933eca54-775b-490f-a5b5-f9ce9f149dad)

Closes #70

2024-12-17 09:13 UTC, danlechambre requested changes
Hey @aditya000028 I've requested a few changes here that should take us closer to what we're after.

Thanks

Dan

2024-12-17 09:13 UTC, danlechambre commented on src/ui/PageHeader.astro
> +      >
We can massively simplify this now. Let's go with the following:
```suggestion
      <h1 class:list={["mx-3 -mt-8 md:mx-10 md:-mt-14 mb-3 md:mb-6"]}>
```
That should give us a similar effect without the `absolute` positioning

2024-12-18 03:16 UTC, aditya000028 commented on src/ui/PageHeader.astro
> +        <img
You're right. I have Prettier installed from before but it did not format it correctly for some reason. I played around with the settings right now, along with taking a look at the comment you linked, and hopefully it's good now.

2024-12-18 03:17 UTC, aditya000028 commented
Thanks for your comments @danlechambre . I have just addressed the changes.

2024-12-18 23:26 UTC, danlechambre approved these changes
That's great. Many thanks

2024-12-19 05:19 UTC, merged